--https://school.programmers.co.kr/learn/courses/30/lessons/144855
SELECT b.CATEGORY, (SUM(s.SALES)) AS 'TOTAL_SALES' FROM BOOK b JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID 
WHERE s.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY b.CATEGORY
ORDER BY B.CATEGORY ASC;
